language: node_js
before_install: npm install -g mocha
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id: AKIAJN7ZXY2IBJ63OOXA
  secret_access_key:
    secure: aYvmU7qGRwkkMSYB4BocGuwyvUTA73mZ70OD2YTDhFQsoa3Fq9E+GFZho2dWyiRnIYvq6I8/a7V036c0NkdFs9St73PvtMcZce9B4gfOjaKnrGG9y5TI6x6hAKKFk3eUF+sklEgKnf8lxdjtXLD2DjyuLp8U9sMmNSOXmo1kfwhEdYmNWHesP4kW1M8z8uaPnfChlshFzZ7Atcf3ZITl+Pm/8gA9qiEcKuZ57yMqH/S+IpD6KbAAbGm4fKlRQomwu48FfIWyB+aNh4wZMd6vQ6+zW5G8tzj6JXBV6VDOPTe1S+zHjM4dq1Ln6UOzEHMJTrmWEqt3tGeuewhYeOjco/MlyaY1Br756jsFdEYV3+46Xk0uXG/V1aTVXzb0WhS0T/wdYbxBDyc5bobldD5oK0+st/N6xr7xDnzCd87KRx1CmftxorBTWpf99tOl6vC5t6bDOM4b+2n2Btm0aKFuUJAcusAeZQnNuj9Z/A5QtIr1dz3yMYdgnCBPGTqoqQZQwDpxoWTd5UumIjbssUPEcBWgDwsCt1MnKQ5tHW+GV2dhXylRzQ1EPSDkkuF0eepgZxEYFw2hw/7v6KLPm97kS+/W+O5GkQnf6RhbaPNUnC2f8xY6FBG4wpTzDyBx0OJAFUrbTBYKeG7212HNCwpdJ9xDikwrhuMXndbyiDbAj6E=
  bucket: deploy-weeia
  upload-dir: wozniakout
  acl: public_read
  on:
    repo: piotrek92/ciWorker
